# Generated by Django 6.0.1 on 2026-02-11 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registration_end_event_registration_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
