# Generated by Django 6.0.1 on 2026-02-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_assigned_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_teachers',
        ),
    ]
