# Generated by Django 6.0.1 on 2026-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_rejection_reason_eventfeedback_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_venue_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
