# Generated by Django 6.0.1 on 2026-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_ai_venue_reason_event_ai_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_crowd_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='crowd_confidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='predicted_crowd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
