# Generated by Django 6.0.1 on 2026-06-01 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_ai_crowd_reason_event_crowd_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_organizers',
            field=models.ManyToManyField(blank=True, related_name='co_organized_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
